name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    # The default timeout for each job is 6 hours, we set it to 2 hours instead
    # Long enough to tell us something's wrong, short enough to catch it early
    timeout-minutes: 120

    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1.11'
          - '1.12'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-15-intel # Intel (x64) runner
        arch:
          - x64
        include:
          # Keep Windows x86 coverage if needed
          - os: windows-latest
            version: '1.10'
            arch: x86
          # macOS ARM64 (Apple Silicon)
          - os: macos-latest
            version: '1'
            arch: aarch64

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: julia-actions/setup-julia@v3
        with:
          show-versioninfo: true
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: julia-actions/cache@v3
        with:
          delete-old-caches: false # avoids extra permissions

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@latest
