# This workflow tests that the pre-commit hook works as expected.
name: PreCommitHooks
on:
  push:
    tags:
      - '*'
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  pc-julia-formatter:
    name: julia-formatter hook
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'

      - name: Install checked out JuliaFormatter in global env
        run: |
          julia -e 'using Pkg; Pkg.add(; path=".")'

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Test pre-commit hook
        working-directory: .github/workflows/pre-commit
        run: |
          # Run pre-commit hook, check that it fails.
          # pre-commit try-repo will fail if the hook makes changes
          pipx run pre-commit try-repo ../../../ julia-formatter --files main.jl --verbose && exit 1

          # Check that the file was changed.
          git diff --exit-code main.jl && exit 1

          # Check that running the hook again succeeds.
          pipx run pre-commit try-repo ../../../ julia-formatter --files main.jl --verbose


  pc-jlfmt:
    name: jlfmt hook
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Check for graceful error if jlfmt is not installed
        working-directory: .github/workflows/pre-commit
        run: |
          # At this point, jlfmt won't be on PATH since the GitHub runner
          # doesn't automatically add Julia apps to PATH. This is intentional,
          # since it lets us check that there is a nice error message if jlfmt
          # is not on PATH.
          output=$(pipx run pre-commit try-repo ../../../ jlfmt --files main.jl --verbose 2>&1 || true)
          echo "$output" | grep -q "make sure that jlfmt is on your PATH" || { echo "Expected graceful error message when jlfmt was not found"; exit 1; }

      - uses: julia-actions/setup-julia@v3
        with:
          version: '1'

      - name: Install jlfmt app
        # Need to explicitly add registry because of
        # https://github.com/JuliaLang/Pkg.jl/issues/4360 which is not
        # backported to 1.12 yet
        run:
          julia -e 'using Pkg; Pkg.Registry.add("General"); Pkg.Apps.add(; path=pwd())'

      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Test pre-commit hook
        working-directory: .github/workflows/pre-commit
        run: |
          # Run pre-commit hook, check that it fails.
          # pre-commit try-repo will fail if the hook makes changes
          pipx run pre-commit try-repo ../../../ jlfmt --files main.jl --verbose && exit 1

          # Check that the file was changed.
          git diff --exit-code main.jl && exit 1

          # Check that running the hook again succeeds.
          pipx run pre-commit try-repo ../../../ jlfmt --files main.jl --verbose

      - name: Test pre-commit hook with --jlfmt-path argument
        working-directory: .github/workflows/pre-commit
        run: |
          # Move the jlfmt binary to somewhere else
          mv ~/.julia/bin/jlfmt ~/.julia/bin/jlfmt-moved

          # Reset the test file
          git checkout main.jl

          # Add --jlfmt-path arg to the existing jlfmt hook. pre-commit
          # try-repo doesn't allow passing hook arguments via the command line,
          # so we inject it directly into .pre-commit-hooks.yaml. A tad ugly.
          sed -i '/^- id: jlfmt$/a\  args: ["--jlfmt-path=~/.julia/bin/jlfmt-moved"]' ../../../.pre-commit-hooks.yaml

          # Run pre-commit hook, check that it fails.
          pipx run pre-commit try-repo ../../../ jlfmt --files main.jl --verbose && exit 1

          # Check that the file was changed.
          git diff --exit-code main.jl && exit 1

          # Check that running the hook again succeeds.
          pipx run pre-commit try-repo ../../../ jlfmt --files main.jl --verbose
